<h1>Numpy</h1>

<p><span style="font-size: 14pt; color: #843fa1;"><strong>Numpy</strong> is a <strong>Python</strong> <strong>Library </strong>that <strong>specializes</strong> in working with <strong>arrays</strong> (lists) of data.</span></p>
<ul>
<li><span style="font-size: 14pt; color: #843fa1;">It can be up to <strong>50% faster </strong>than working with <strong>lists</strong></span></li>
<li><span style="font-size: 14pt; color: #843fa1;">It also has <strong>functions</strong> for working in domain of l<strong>inear algebra, fourier transform</strong>, and <strong>matrices</strong></span></li>
<li><span style="font-size: 14pt; color: #843fa1;">Numpy stands for N<strong>umerical Python</strong> and is written in C and C++</span></li>
<li><span style="font-size: 14pt; color: #843fa1;">Unlike lists, <strong>numpy</strong> array <strong>cannot</strong> <strong>mix</strong> <strong>data</strong> <strong>types</strong></span></li>
<li><span style="font-size: 14pt; color: #843fa1;"><a href="https://numpy.org/" target="_blank" rel="noopener">https://numpy.org/</a></span></li>
</ul>
<p><span style="font-size: 14pt; color: #843fa1;">Numpy is <strong>included</strong> in the <strong>Anacond</strong>a version of Python</span></p>
<p><span style="font-size: 14pt; color: #843fa1;">However, it can be installed by :</span></p>
<p><span style="font-size: 14pt; color: #843fa1;">Pip</span></p>
<p><strong><span style="color: #843fa1;"><span style="font-size: 18.6667px;">pip install numpy</span></span></strong></p>
<p>&nbsp;</p>
<p><span style="font-size: 14pt; color: #843fa1;"><span style="color: #843fa1;"><span style="font-size: 18.6667px;">Conda</span></span></span></p>
<p><strong><span style="color: #843fa1;"><span style="font-size: 18.6667px;">conda install numpy</span></span></strong></p>
<p>&nbsp;</p>

<div style="border: 1px solid blue; padding: 10px">
<p><span style="font-size: 14pt; color: #843fa1;">As <strong>powerful</strong> as <strong>Numpy</strong> is, we have a tendency to use <strong>Pandas</strong> more in <strong>Data Analytics and Sciecne</strong>.&nbsp; As such, we will mostly cover <strong>Numpy</strong> topics that <strong>you will encounter.</strong>&nbsp;&nbsp;</span></p>
<p><span style="font-size: 14pt; color: #843fa1;">That being said, there are many tasks that Numpy is very good at and if Numpy seems more logical, by all means, feel free to utilize Numpy as you see fit.&nbsp;</span></p>
</div>

In [ ]:
https://www.w3schools.com/python/numpy/default.asp

<div style="border: 1px solid blue; padding: 10px">
<p><span style="font-size: 14pt; color: #843fa1;">The first step is to <strong>import</strong> the <strong>numpy</strong> library.&nbsp; I like to keep all my imports in a cell at the <strong>top</strong> of the <strong>program</strong>.&nbsp; This way, if I need to make <strong>changes</strong>, I do not need to <strong>search</strong> through-out the program to find the <strong>different</strong> libraries.&nbsp;&nbsp;</span></p>
<p><span style="font-size: 14pt; color: #843fa1;">Before you can import the libaray, it obviosly has to be <strong>installed</strong>.&nbsp; Please see the cell above for info on installing numpy.</span></p>
<p><span style="font-size: 14pt; color: #843fa1;">Note that is is <strong>common</strong> to install numpy has&nbsp; give it an <strong>alias</strong> of <strong>np</strong>.&nbsp; This is not required, but very common in most fields.&nbsp;&nbsp;</span></p>\
</div>

In [1]:
import numpy as np  # import numpy and give it an alias of np


<h2>1 Dimensional Array</h2>

<div style="border: 1px solid blue; padding: 10px;">
<p><span style="color: #843fa1; font-size: 14pt;">Let's <strong>create</strong> a 1<strong>-Dimenional array</strong>, usually referred to as <strong>1-D</strong></span></p>
</div>

In [29]:
#  Create a 1 dimensional numpy array
arr = np.array([1, 2, 3, 4, 5])
# p;rint results
print(arr)
# chec the numer of dimensions
print(arr.ndim)
# ehck dat atype
print(type(arr))
print(arr[0])
# Slicing
print(arr[1:4])


for x in arr:
    print(x)

[1 2 3 4 5]
1
<class 'numpy.ndarray'>
1
[2 3 4]
1
2
3
4
5


<p><span style="font-size: 14pt; color: #843fa1;">Note in the printed out <strong>1-D array</strong>, unlike Python lists, there are <strong>spaces</strong> between the <strong>elements</strong> of the <strong>array</strong>, not commas.&nbsp; That is one way when you print out an array or list, you can easily tell which you have.&nbsp; For processing, this does not make a difference<br /><br /></span></p>

<h2>2 Dimensional Array</h2>

<div style="border: 1px solid blue; padding: 10px;">
<p><span style="font-size: 14pt; color: #843fa1;">Ok, now lets create a 2-D array</span></p>
<p><span style="font-size: 14pt; color: #843fa1;">These can be extremely useful for keeping track of multi-dimensional data, like data in a time series, geographical data or for multi-feature machine learing.</span></p>
</div>

In [35]:
# Create 2 dimensional array
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)
print(arr.shape)
print(arr)
print('2nd element on 1st row: ', arr[0, 1])

# slicing
print(arr[1, 1:3])
for x in arr:
    print(x)
    
for x in arr:
    for y in x:
        print(y)

2
(2, 3)
[[1 2 3]
 [4 5 6]]
2nd element on 1st row:  2
[5 6]
[1 2 3]
[4 5 6]
1
2
3
4
5
6


<h2>3 Dimensions</h2>

<p><span style="font-size: 14pt; color: #843fa1;">And, finally, a 3-D array</span></p>
<p><span style="font-size: 14pt; color: #843fa1;">The can be useful for geographic data in a time series and some multi-feature machine learing that is multi-feature data in time series or color images.</span></p>

In [34]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr.ndim)
print(arr)
print(arr[0, 1, 2])

for x in arr:
    print(x)
    
for x in arr:
    for y in x:
        print(y)
        
for x in arr:
    for y in x:
        for z in y:
            print(z)

3
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
6
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[1 2 3]
[4 5 6]
[1 2 3]
[4 5 6]
1
2
3
4
5
6
1
2
3
4
5
6


<h2>Reshaping Arrays</h2>


<p><span style="font-size: 14pt; color: #843fa1;">It is not uncommon for certain <strong>libraries</strong> or <strong>functions</strong> to need <strong>data</strong> to be of a <strong>certain shape</strong>.&nbsp; For example, many <strong>machine</strong> <strong>learning</strong> models need the data to be in a <strong>1-D</strong> array.&nbsp; Being able to <strong>reshape</strong> the <strong>arrays</strong>, correctly, is an <strong>important</strong> <strong>skill</strong>.&nbsp; Luckily, <strong>Numpy</strong> makes this very <strong>easy</strong>.</span><br /><br /></p>

In [19]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)
print(newarr.shape)

newarr = arr.reshape(2,6)
print(newarr.shape)
print(newarr)

newarr = arr.reshape(6,2)
print(newarr.shape)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
(4, 3)
(2, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(6, 2)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [21]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(3,2)
print(newarr)

[[1 2]
 [3 4]
 [5 6]]


In [25]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(1,-1)
print(newarr.shape)
print(newarr)

(1, 6)
[[1 2 3 4 5 6]]


In [27]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1,1)
print(newarr.shape)
print(newarr)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr.shape)
print(newarr)

(6,)
[1 2 3 4 5 6]
